# -*- coding: utf-8 -*-
"""detecting-disease-yolov8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ftzUEYtWRWLvRhAw-CEZudPVa_e7ylfE
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics

!pip install roboflow

from ultralytics import YOLO
import os
from IPython.display import display, Image
from IPython import display

display.clear_output()

# ✅ This is correct
!yolo checks

from roboflow import Roboflow
rf = Roboflow(api_key="Id8qoqNPEqovRJN8jiVs")
project = rf.workspace("first-one-opr0f").project("detecting-diseases-vgzzr")
version = project.version(1)
dataset = version.download("yolov8")

!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=50 imgsz=640 project='/content/drive/MyDrive/yolov8_output_2'

!yolo task=detect mode=predict model='/content/drive/MyDrive/yolov8_output_2/train/weights/best.pt' conf=0.25 source='{dataset.location}/test/images' save=True

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'/content/runs/detect/predict/*.jpg')[:31]:
      display(Image(filename=image_path, height=600))
      print("\n")